# Group Stock
Resources related to **stocks** in the API.

## Strain collection [/strains]
It supports the following JSONAPI query parameters

* **include:** All the relationships given below can be included. Those who are not
  mentioned specifically are expected to follow the similar data structures.
  + dbxrefs
  + phenotypes
  + genotypes
  + characteristics
  + inventories
  + publications
  + orders
  + parents

* **sparse fieldsets:** Attributes of all the relationships are allowed.
* **filter:**


### List of all strains [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Body

            {
               "data": [
                    {
                        "type": "strains",
                        "id": "DBS0236225",
                        "attributes": {
                            "name": "HL27",
                            "description": "partial stalky mutant in marked strains",
                            "category": "strain"
                        },
                        "relationships": {
                            "dbxrefs": {
                                "links": {
                                    "related": "/strains/DBS0236225/dbxrefs"
                                }
                            },
                            "phenotypes": {
                                "links": {
                                    "related": "/strains/DBS0236225/phenotypes"
                                }
                            },
                            "genotypes": {
                                "links": {
                                    "related": "/strains/DBS0236225/genotypes"
                                }
                            },
                            "characteristics": {
                                "links": {
                                    "related": "/strains/DBS0236225/characteristics"
                                }
                            },
                            "inventories": {
                                "links": {
                                    "related": "/strains/DBS0236225/inventories"
                                }
                            },
                            "publications": {
                                "links": {
                                    "related": "/strains/DBS0236225/publictions"
                                }
                            },
                            "orders": {
                                "links": {
                                    "related": "/strains/DBS0236225/orders"
                                }
                            },
                            "parents": {
                                "links": {
                                    "related": "/strains/DBS0236225/parents"
                                }
                            }
                        },
                        {
                            #another stock item
                        }
                    ],
                "links": {
                  "self": "/strains?page[number]=3&page[size]=3",
                  "first": "/strains?page[number]=1&page[size]=3",
                  "prev": "/strains?page[number]=2&page[size]=3",
                  "next": "/strains?page[number]=4&page[size]=3",
                  "last": "/strains?page[number]=12&page[size]=2"
                },
                "meta": {
                    "pagination": {
                        "records": 1000,
                        "total": 100,
                        "size": 10,
                        "number": 3
                    }
                }
            }


+ Response 400 (application/vnd.api+json)
Below, a generic JSONAPI error response is given that will be identical for any
http 400 error with supported query parameter. The following value for title
field could appear depending on the error.

    * Invalid include query parameter
    * Invalid fieldsets query parameter
    * Invalid filter query parameter

    + Body

            {
              "errors": [{
                "status": "400",
                "source": { "parameter": "include or fieldsets or filter" },
                "title": "Invalid include/fieldsets/filter query parameter",
                "detail": "...."
              }]
            }

+ Response 500 (application/vnd.api+json)
The following value for title field could appear depending on the error.
    
    * Database query error
    * Json encoding error
    * Structure marshalling error

    + Body

            {
              "errors": [{
                "status": "500",
                "title": "Database query error",
                "detail": "...."
              }]
            }


+ Response 404 (application/vnd.api+json)

    + Body

            {
              "errors": [{
                "status": "404",
                "title": "Resource not found",
                "detail": "...."
              }]
            }


+ Request with include query parameter (application/vnd.api+json)
    
   * Includes `phenotypes` in query parameter as an example

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Body

            {
               "data": [
                    {
                        "type": "strains",
                        "id": "DBS0236225",
                        "attributes": {
                            "name": "HL27",
                            "description": "partial stalky mutant in marked strains",
                            "category": "strain"
                        },
                        "relationships": {
                            "dbxrefs": {
                                "links": {
                                    "related": "/strains/DBS0236225/dbxrefs"
                                }
                            },
                            "phenotypes": {
                                "links": {
                                    "related": "/strains/DBS0236225/phenotypes"
                                },
                                "data": [
                                    { "type": "phenotypes", "id": "DSC_PHENO0007441"},
                                    { "type": "phenotypes", "id": "DSC_PHENO0008001"}
                                ]
                            },
                            "genotypes": {
                                "links": {
                                    "related": "/strains/DBS0236225/genotypes"
                                }
                            },
                            "characteristics": {
                                "links": {
                                    "related": "/strains/DBS0236225/characteristics"
                                }
                            },
                            "inventories": {
                                "links": {
                                    "related": "/strains/DBS0236225/inventories"
                                }
                            },
                            "publications": {
                                "links": {
                                    "related": "/strains/DBS0236225/publictions"
                                }
                            },
                            "orders": {
                                "links": {
                                    "related": "/strains/DBS0236225/orders"
                                }
                            },
                            "parents": {
                                "links": {
                                    "related": "/strains/DBS0236225/parents"
                                }
                            }
                        },
                        "links": {
                            "self": "/strains/DBS0236225"
                        }
                    }
                    {
                       #another stock item
                    }
                ],
                "links": {
                  "self": "/strains?page[number]=3&page[size]=3",
                  "first": "/strains?page[number]=1&page[size]=3",
                  "prev": "/strains?page[number]=2&page[size]=3",
                  "next": "/strains?page[number]=4&page[size]=3",
                  "last": "/strains?page[number]=12&page[size]=2"
                },
                "meta": {
                    "pagination": {
                        "records": 1000,
                        "total": 100,
                        "size": 10,
                        "number": 3
                    }
                },
                "included": [
                    {
                        "links": {
                            "self": "/phenotypes/DSC_PHEN0007441"
                        },
                        "type": "phenotypes",
                        "id": "DSC_PHEN0007441",
                        "attributes": {
                            "name": "D.discoideum unique phenotypes",
                            "observation": "abolished aggreation",
                            "phen_attribute": "decreased occurence",
                            "value": "For some reason very less aggreation",
                            "cvalue": "I do not know",
                            "evidence": "fruiting body development"
                        },
                        "relationships": {
                            "properties": {
                                "links": {
                                    "related": "/phenotypes/DSC_PHEN0007441/properties"
                                }
                            }
                        }
                    } 
                ]
            }

