# Group Publication
Resources related to **publications** in the API.


## Publication [/publications/{publication_id}]
+ Parameters
    + publication_id: 26099919 (number, required) - The id will be primarily
      [pubmed identifier](https://en.wikipedia.org/wiki/PubMed#PubMed_identifier).
      However for handful of non-published resources, internally generated
      identifiers will be used. 


### Retrieve a specific publication [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Body

            {
                "data": {
                    "links": {
                        "self": "/publications/26099919"
                    },
                    "type": "publications",
                    "id": "26088819",
                    "attributes": {
                        "doi": "10.1002/dvg.22867",
                        "title": "dictyBase 2015: Expanding data and annotations in a new software environment",
                        "abstract": "dictyBase is the model organism database ......",
                        "journal": "Genesis",
                        "year": "2015",
                        "volume": "12",
                        "pages": "765-80",
                        "month": "june",
                        "issn": "1526-968X",
                        "pub_type": "journal_article",
                        "source": "pubmed",
                        "issue": "8",
                        "status": "ppublish"
                    },
                    "relationships": {
                        "authors": {
                            "links": {
                                "related": "/publication/26099919/authors"
                            }
                        }
                    }
                }
            }


+ Response 400 (application/vnd.api+json)
Below, a generic JSONAPI error response is given that will be identical for any
http 400 error with supported query parameter. The following value for title
field could appear depending on the error.

    * Invalid include query parameter
    * Invalid fieldsets query parameter

    + Body

            {
              "errors": [{
                "status": "400",
                "source": { "parameter": "include or fieldsets or filter" },
                "title": "Invalid include/fieldsets/filter query parameter",
                "detail": "...."
              }]
            }

+ Response 500 (application/vnd.api+json)
The following value for title field could appear depending on the error.
    
    * Database query error
    * Json encoding error
    * Structure marshalling error

    + Body

            {
              "errors": [{
                "status": "500",
                "title": "Database query error",
                "detail": "...."
              }]
            }


+ Response 404 (application/vnd.api+json)

    + Body

            {
              "errors": [{
                "status": "404",
                "title": "Resource not found",
                "detail": "...."
              }]
            }


### Delete a specific publication [DELETE]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json

+ Response 204

+ Response 404 (application/vnd.api+json)

    + Body

            {
              "errors": [{
                "status": "404",
                "title": "resource not found"
                "detail": "......."
              }]
            }


### Update a specific publication [PATCH]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json  

    + Body

            {
                "data": {
                    "type": "publications",
                    "id": "26088819",
                    "attributes": {
                        "doi": "10.1002/dvg.22867",
                        "title": "dictyBase 2015: Expanding data and annotations in a new software environment",
                        "abstract": "dictyBase is the model organism database ......",
                        "journal": "Genesis",
                        "year": "2015",
                        "volume": "12",
                        "pages": "765-80",
                        "month": "june",
                        "issn": "1526-968X",
                        "pub_type": "journal_article",
                        "source": "pubmed",
                        "issue": "8",
                        "status": "ppublish"
                    }
                }
            }

+ Response 204

+ Response 404 (application/vnd.api+json)

    + Body

            {
              "errors": [{
                "status": "404",
                "title": "resource not found"
                "detail": "......."
              }]
            }

## Publication collection [/publications]
It supports the following JSONAPI query parameters

* **include:** All the relationships given below can be included. Those who are not
  mentioned specifically are expected to follow the similar data structures.
  + authors

* **filter:**

###  List of all publications [GET]
+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Body

                {
                    "data": [
                        {
                            "links": {
                                "self": "/publications/26088819"
                            }
                            "type": "publications",
                            "id": "26088819",
                            "attributes": {
                                "doi": "10.1002/dvg.22867",
                                "title": "dictyBase 2015: Expanding data and annotations in a new software environment",
                                "abstract": "dictyBase is the model organism database ......",
                                "journal": "Genesis",
                                "year": "2015",
                                "volume": "12",
                                "pages": "765-80",
                                "month": "june",
                                "issn": "1526-968X",
                                "source": "pubmed",
                                "issue": "8",
                                "status": "ppublish",
                                "pub_type": "journal_article"
                            },
                            "relationships": {
                                "authors": {
                                    "links": {
                                        "related": "/publication/26088819/authors"
                                    }
                                }
                            }
                        }, 
                        {
                            "links": {
                                "self": "/publications/23172289"
                            }
                            "type": "publications",
                            "id": "23172289",
                            "attributes": {
                                "doi": "10.1093/nar/gks1064",
                                "title": "dictyBase 2013: Integrating multiple dictyostelid species",
                                "abstract": "dictyBase is the model organism database ......",
                                "journal": "Nucleic Acids Research",
                                "year": "2013",
                                "volume": "41",
                                "pages": "676-80",
                                "issue": "18",
                                "month": "jan",
                                "issn": "1362-4962",
                                "source": "pubmed",
                                "status": "epublish",
                                "pub_type": "journal_article"
                            },
                            "relationships": {
                                "authors": {
                                    "links": {
                                        "related": "/publication/23172289/authors"
                                    }
                                }
                            }
                        }
                    ],
                    "links": {
                        "self": "/publications?pageNum=6&pageSize=10",
                        "next": "/publications?pageNum=7&pageSize=10",
                        "prev": "/publications?pageNum]=5&pageSize=10",
                        "last": "/publications?pageNum=80&pageSize=10",
                        "first": "/publications?pageNum=1&pageSize=10"
                    },
                    "meta": {
                        "pagination": {
                            "records": 800,
                            "total": 80,
                            "size": 10,
                            "number": 6
                        }
                    }
                }


+ Response 400 (application/vnd.api+json)
Below, a generic JSONAPI error response is given that will be identical for any
http 400 error with supported query parameter. The following value for title
field could appear depending on the error.

    * Invalid include query parameter
    * Invalid fieldsets query parameter
    * Invalid filter query parameter

    + Body

            {
              "errors": [{
                "status": "400",
                "source": { "parameter": "include or fieldsets or filter" },
                "title": "Invalid include/fieldsets/filter query parameter",
                "detail": "...."
              }]
            }

+ Response 500 (application/vnd.api+json)
The following value for title field could appear depending on the error.
    
    * Database query error
    * Json encoding error
    * Structure marshalling error

    + Body

            {
              "errors": [{
                "status": "500",
                "title": "Database query error",
                "detail": "...."
              }]
            }


+ Response 404 (application/vnd.api+json)

    + Body

            {
              "errors": [{
                "status": "404",
                "title": "Resource not found",
                "detail": "...."
              }]
            }


+ Request with include query parameter (application/vnd.api+json)
    
   * Includes `authors` in query parameter as an example

    + Headers

            Accept: application/vnd.api+json

+ Response 200 (application/vnd.api+json)

    + Body

            {
               "data": [
                    {
                        "type": "stocks",
                        "id": "DBS0236225",
                        "attributes": {
                            "name": "HL27",
                            "description": "partial stalky mutant in marked strains",
                            "category": "strain"
                        },
                        "relationships": {
                            "dbxrefs": {
                                "links": {
                                    "related": "/stocks/DBS0236225/dbxrefs"
                                }
                            },
                            "phenotypes": {
                                "links": {
                                    "related": "/stocks/DBS0236225/phenotypes"
                                },
                                "data": [
                                    { "type": "phenotypes", "id": "DSC_PHENO0007441"},
                                    { "type": "phenotypes", "id": "DSC_PHENO0008001"}
                                ]
                            },
                            "genotypes": {
                                "links": {
                                    "related": "/stocks/DBS0236225/genotypes"
                                }
                            },
                            "characteristics": {
                                "links": {
                                    "related": "/stocks/DBS0236225/characteristics"
                                }
                            },
                            "inventories": {
                                "links": {
                                    "related": "/stocks/DBS0236225/inventories"
                                }
                            },
                            "publications": {
                                "links": {
                                    "related": "/stocks/DBS0236225/publictions"
                                }
                            },
                            "orders": {
                                "links": {
                                    "related": "/stocks/DBS0236225/orders"
                                }
                            },
                            "parents": {
                                "links": {
                                    "related": "/stocks/DBS0236225/parents"
                                }
                            }
                        },
                        "links": {
                            "self": "/stocks/DBS0236225"
                        }
                    }
                    {
                       #another stock item
                    }
                ],
                "links": {
                  "self": "/stocks?page[number]=3&page[size]=3",
                  "first": "/stocks?page[number]=1&page[size]=3",
                  "prev": "/stocks?page[number]=2&page[size]=3",
                  "next": "/stocks?page[number]=4&page[size]=3",
                  "last": "/stocks?page[number]=12&page[size]=2"
                },
                "meta": {
                    "pagination": {
                        "records": 1000,
                        "total": 100,
                        "size": 10,
                        "number": 3
                    }
                },
                "included": [
                    {
                        "links": {
                            "self": "/phenotypes/DSC_PHEN0007441"
                        },
                        "type": "phenotypes",
                        "id": "DSC_PHEN0007441",
                        "attributes": {
                            "name": "D.discoideum unique phenotypes",
                            "observation": "abolished aggreation",
                            "phen_attribute": "decreased occurence",
                            "value": "For some reason very less aggreation",
                            "cvalue": "I do not know",
                            "evidence": "fruiting body development"
                        },
                        "relationships": {
                            "properties": {
                                "links": {
                                    "related": "/phenotypes/DSC_PHEN0007441/properties"
                                }
                            }
                        }
                    } 
                ]
            }


### Create a new publication [POST]
A new publication resource can be created either by ...  
- supplying an id: The value should be in `data.attributes.pubid` field.  
- not supplying an id: In this case one will be created by the server.

The example below represents the first case.

+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json

    + Body

            {
                "data": {
                    "type": "publications",
                    "attributes": {
                        "doi": "10.1002/dvg.22867",
                        "title": "dictyBase 2015: Expanding data and annotations in a new software environment",
                        "abstract": "dictyBase is the model organism database ......",
                        "journal": "Genesis",
                        "year": "2015",
                        "volume": "12",
                        "pages": "765-80",
                        "month": "june",
                        "issn": "1526-968X",
                        "pub_type": "journal_article",
                        "source": "pubmed",
                        "pubid": "26088819",
                        "issue": "8",
                        "status": "ppublish"
                    }
                }
            }

+ Response 201 (application/vnd.api+json)  

    + Headers

            Location: /publications/26088819  

    + Body  

            {
                "data": {
                    "links": {
                        "self": "/publications/26088819"
                    },
                    "type": "publications",
                    "id": "26088819",
                    "attributes": {
                        "doi": "10.1002/dvg.22867",
                        "title": "dictyBase 2015: Expanding data and annotations in a new software environment",
                        "abstract": "dictyBase is the model organism database ......",
                        "journal": "Genesis",
                        "year": "2015",
                        "volume": "12",
                        "pages": "765-80",
                        "month": "june",
                        "issn": "1526-968X",
                        "pub_type": "journal_article",
                        "source": "pubmed",
                        "issue": "8",
                        "status": "ppublish"
                    }
                }
            }


+ Response 409 (application/vnd.api+json)

    + Body

            {
              "errors": [{
                "status": "409",
                "source": {"pointer": "/data/attributes/pubid"},
                "links": {"about": "/publications/26088819"}
                "title": "Resource exists",
                "detail": "id 26088819 exist, resource cannot not created",
              }]
            }
